### ISSUE TITLE
Release the bar file

### ISSUE THREAD

**Issue by vaskas** [diegotid/backpack-blackberry#1]
Hi Diego,
Thanks heaps for releasing the app under GPLv3! Do you mind also attaching the compiled application bar?

**Comment by diegotid** [comment]
Hi Vaskas

Thank you for your interest. Unfortunately I don't keep the binaries with me. I guess you don't have a BlackBerry account to get the bar file from its app store (link on the repo's readme [this one](https://appworld.blackberry.com/webstore/content/20399673)).

I don't have the IDE installed either, but you can give a try if you want and compile the file yourself. It easy... get the IDE at [BlackBerry's developer site](https://developer.blackberry.com/native/download/)

Let me know if I can help with anything else
Best regards
Diego
